INSERT INTO `broadleaf`.`BLC_CURRENCY` (`CURRENCY_CODE`, `DEFAULT_FLAG`, `FRIENDLY_NAME`) VALUES ('INR', '1', 'Indian Rupee');
UPDATE `broadleaf`.`BLC_CURRENCY` SET `DEFAULT_FLAG`='0' WHERE `CURRENCY_CODE`='USD';

UPDATE `broadleaf`.`BLC_LOCALE` SET `DEFAULT_FLAG`='1', `FRIENDLY_NAME`='Indian Rupee', `USE_IN_SEARCH_INDEX`='', `CURRENCY_CODE`='INR' WHERE `LOCALE_CODE`='en_US';
